export { default as School } from "./School";
export { default as User } from "./User";
export { default as Student } from "./Student";
export { default as Attendance } from "./Attendance";
export { default as LeaveRequest } from "./LeaveRequest";
export { default as Notification } from "./Notification";
export { default as Visitor } from "./Visitor";
export { default as Room } from "./Room";
export { default as RoomBooking } from "./RoomBooking";
export { default as Holiday } from "./Holiday";
export { default as Timetable } from "./Timetable";
export { default as QRToken } from "./QRToken";
export { default as EmergencyAlert } from "./EmergencyAlert";
export { default as Setting } from "./Setting";
export { default as Token } from "./Token";
export { default as Department } from "./Department";
export { default as Semester } from "./Semester";
export { default as Subject } from "./Subject";
export { default as SubjectAttendance } from "./SubjectAttendance";
export { default as TeacherAttendance } from "./TeacherAttendance";
export { default as Salary } from "./Salary";
export { FeeStructure, FeePayment } from "./Fee";
export { Exam, Grade } from "./Exam";
export { default as AcademicYear } from "./AcademicYear";
export { default as Transport } from "./Transport";
export { LibraryBook, BookIssue } from "./Library";
export { Hostel, HostelAllocation } from "./Hostel";
export { default as Promotion } from "./Promotion";
export { default as FacultyWorkload } from "./FacultyWorkload";
export { default as Backup } from "./Backup";
export { default as Role } from "./Role";
export { default as Payment } from "./Payment";
export { default as Assignment } from "./Assignment";
export { default as OnlineExam } from "./OnlineExam";
export { default as Event } from "./Event";
export { default as Message } from "./Message";
export { default as Conversation } from "./Conversation";
export { default as Circular } from "./Circular";
export { default as PushSubscription } from "./PushSubscription";
export { default as StudentDocument } from "./StudentDocument";
export { default as DiaryEntry } from "./DiaryEntry";
export { default as TeacherEvaluation } from "./TeacherEvaluation";
export { default as AuditLog } from "./AuditLog";
export { default as Inventory } from "./Inventory";
export { default as Alumni } from "./Alumni";
export { default as AcademicCalendar } from "./AcademicCalendar";
export { default as SchoolBranding } from "./SchoolBranding";

export type { ISchool } from "./School";
export type { IUser } from "./User";
export type { IStudent } from "./Student";
export type { IAttendance } from "./Attendance";
export type { ILeaveRequest } from "./LeaveRequest";
export type { INotification } from "./Notification";
export type { IVisitor } from "./Visitor";
export type { IRoom } from "./Room";
export type { IRoomBooking } from "./RoomBooking";
export type { IHoliday } from "./Holiday";
export type { ITimetable } from "./Timetable";
export type { IQRToken } from "./QRToken";
export type { IEmergencyAlert } from "./EmergencyAlert";
export type { ISetting } from "./Setting";
export type { IToken } from "./Token";
export type { IDepartment } from "./Department";
export type { ISemester } from "./Semester";
export type { ISubject } from "./Subject";
export type { ISubjectAttendance } from "./SubjectAttendance";
export type { ITeacherAttendance } from "./TeacherAttendance";
export type { ISalary } from "./Salary";
export type { IFeeStructure, IFeePayment } from "./Fee";
export type { IExam, IGrade } from "./Exam";
export type { IAcademicYear } from "./AcademicYear";
export type { ITransport } from "./Transport";
export type { ILibraryBook, IBookIssue } from "./Library";
export type { IHostel, IHostelAllocation } from "./Hostel";
export type { IPromotion } from "./Promotion";
export type { IFacultyWorkload } from "./FacultyWorkload";
export type { IBackup } from "./Backup";
export type { IRole, IMenuPermission } from "./Role";
export type { IPayment } from "./Payment";
export type { IAssignment } from "./Assignment";
export type { IOnlineExam } from "./OnlineExam";
export type { IEvent } from "./Event";
export type { IMessage } from "./Message";
export type { IConversation } from "./Conversation";
export type { ICircular } from "./Circular";
export type { IPushSubscription } from "./PushSubscription";
export type { IStudentDocument } from "./StudentDocument";
export type { IDiaryEntry } from "./DiaryEntry";
export type { ITeacherEvaluation } from "./TeacherEvaluation";
export type { IInventory } from "./Inventory";
export type { IAlumni } from "./Alumni";
export type { IAcademicCalendar } from "./AcademicCalendar";
export type { ISchoolBranding } from "./SchoolBranding";
